library(CircSpaceTime)
library(circular)
library(CholWishart)
library(coda)
library(dlm)
library(KFAS)
library(MASS)
library(matrixNormal)
library(MCMCpack)
library(mvtnorm)
#library(NHMSAR) # not on cran anymore
library(plotly)
library(rstan)
library(Directional)
#library(ts.extend) # might have to install from archive
